name: diabetes_predictor
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  flutter_local_notifications: ^13.0.0
  charts_flutter: ^0.12.0
  cupertino_icons: ^1.0.2
  logging: ^1.1.0
  logger: ^1.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
